// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.CustomMatch_LobbyPlayers');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.CustomMatch_LobbyPlayer');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rtech.liveapi.CustomMatch_LobbyPlayers.repeatedFields_, null);
};
goog.inherits(proto.rtech.liveapi.CustomMatch_LobbyPlayers, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.CustomMatch_LobbyPlayers.displayName = 'proto.rtech.liveapi.CustomMatch_LobbyPlayers';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.CustomMatch_LobbyPlayers.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.CustomMatch_LobbyPlayers} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.toObject = function(includeInstance, msg) {
  var f, obj = {
playertoken: jspb.Message.getFieldWithDefault(msg, 1, ""),
playersList: jspb.Message.toObjectList(msg.getPlayersList(),
    proto.rtech.liveapi.CustomMatch_LobbyPlayer.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.CustomMatch_LobbyPlayers}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.CustomMatch_LobbyPlayers;
  return proto.rtech.liveapi.CustomMatch_LobbyPlayers.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.CustomMatch_LobbyPlayers} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.CustomMatch_LobbyPlayers}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayertoken(value);
      break;
    case 2:
      var value = new proto.rtech.liveapi.CustomMatch_LobbyPlayer;
      reader.readMessage(value,proto.rtech.liveapi.CustomMatch_LobbyPlayer.deserializeBinaryFromReader);
      msg.addPlayers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.CustomMatch_LobbyPlayers.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.CustomMatch_LobbyPlayers} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayertoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPlayersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.rtech.liveapi.CustomMatch_LobbyPlayer.serializeBinaryToWriter
    );
  }
};


/**
 * optional string playerToken = 1;
 * @return {string}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.getPlayertoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.CustomMatch_LobbyPlayers} returns this
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.setPlayertoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated CustomMatch_LobbyPlayer players = 2;
 * @return {!Array<!proto.rtech.liveapi.CustomMatch_LobbyPlayer>}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.getPlayersList = function() {
  return /** @type{!Array<!proto.rtech.liveapi.CustomMatch_LobbyPlayer>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rtech.liveapi.CustomMatch_LobbyPlayer, 2));
};


/**
 * @param {!Array<!proto.rtech.liveapi.CustomMatch_LobbyPlayer>} value
 * @return {!proto.rtech.liveapi.CustomMatch_LobbyPlayers} returns this
*/
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.setPlayersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.rtech.liveapi.CustomMatch_LobbyPlayer=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rtech.liveapi.CustomMatch_LobbyPlayer}
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.addPlayers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.rtech.liveapi.CustomMatch_LobbyPlayer, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rtech.liveapi.CustomMatch_LobbyPlayers} returns this
 */
proto.rtech.liveapi.CustomMatch_LobbyPlayers.prototype.clearPlayersList = function() {
  return this.setPlayersList([]);
};


