// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.CustomMatch_SetSettings');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.CustomMatch_SetSettings = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rtech.liveapi.CustomMatch_SetSettings, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.CustomMatch_SetSettings.displayName = 'proto.rtech.liveapi.CustomMatch_SetSettings';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.CustomMatch_SetSettings.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.CustomMatch_SetSettings} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.CustomMatch_SetSettings.toObject = function(includeInstance, msg) {
  var f, obj = {
playlistname: jspb.Message.getFieldWithDefault(msg, 1, ""),
adminchat: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
teamrename: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
selfassign: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
aimassist: jspb.Message.getBooleanFieldWithDefault(msg, 5, false),
anonmode: jspb.Message.getBooleanFieldWithDefault(msg, 6, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.CustomMatch_SetSettings;
  return proto.rtech.liveapi.CustomMatch_SetSettings.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.CustomMatch_SetSettings} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlaylistname(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAdminchat(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setTeamrename(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSelfassign(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAimassist(value);
      break;
    case 6:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAnonmode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.CustomMatch_SetSettings.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.CustomMatch_SetSettings} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.CustomMatch_SetSettings.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlaylistname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAdminchat();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getTeamrename();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getSelfassign();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getAimassist();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
  f = message.getAnonmode();
  if (f) {
    writer.writeBool(
      6,
      f
    );
  }
};


/**
 * optional string playlistName = 1;
 * @return {string}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.getPlaylistname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings} returns this
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.setPlaylistname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool adminChat = 2;
 * @return {boolean}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.getAdminchat = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings} returns this
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.setAdminchat = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool teamRename = 3;
 * @return {boolean}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.getTeamrename = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings} returns this
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.setTeamrename = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool selfAssign = 4;
 * @return {boolean}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.getSelfassign = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings} returns this
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.setSelfassign = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional bool aimAssist = 5;
 * @return {boolean}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.getAimassist = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings} returns this
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.setAimassist = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * optional bool anonMode = 6;
 * @return {boolean}
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.getAnonmode = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 6, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.CustomMatch_SetSettings} returns this
 */
proto.rtech.liveapi.CustomMatch_SetSettings.prototype.setAnonmode = function(value) {
  return jspb.Message.setProto3BooleanField(this, 6, value);
};


