// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.LegendUpgradeSelected');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.Player');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.LegendUpgradeSelected = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rtech.liveapi.LegendUpgradeSelected, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.LegendUpgradeSelected.displayName = 'proto.rtech.liveapi.LegendUpgradeSelected';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.LegendUpgradeSelected.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.LegendUpgradeSelected} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.LegendUpgradeSelected.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
category: jspb.Message.getFieldWithDefault(msg, 2, ""),
player: (f = msg.getPlayer()) && proto.rtech.liveapi.Player.toObject(includeInstance, f),
upgradename: jspb.Message.getFieldWithDefault(msg, 4, ""),
upgradedesc: jspb.Message.getFieldWithDefault(msg, 5, ""),
level: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected}
 */
proto.rtech.liveapi.LegendUpgradeSelected.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.LegendUpgradeSelected;
  return proto.rtech.liveapi.LegendUpgradeSelected.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.LegendUpgradeSelected} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected}
 */
proto.rtech.liveapi.LegendUpgradeSelected.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 3:
      var value = new proto.rtech.liveapi.Player;
      reader.readMessage(value,proto.rtech.liveapi.Player.deserializeBinaryFromReader);
      msg.setPlayer(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpgradename(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpgradedesc(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLevel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.LegendUpgradeSelected.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.LegendUpgradeSelected} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.LegendUpgradeSelected.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPlayer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.rtech.liveapi.Player.serializeBinaryToWriter
    );
  }
  f = message.getUpgradename();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUpgradedesc();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string category = 2;
 * @return {string}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Player player = 3;
 * @return {?proto.rtech.liveapi.Player}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.getPlayer = function() {
  return /** @type{?proto.rtech.liveapi.Player} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Player, 3));
};


/**
 * @param {?proto.rtech.liveapi.Player|undefined} value
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
*/
proto.rtech.liveapi.LegendUpgradeSelected.prototype.setPlayer = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.clearPlayer = function() {
  return this.setPlayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.hasPlayer = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string upgradeName = 4;
 * @return {string}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.getUpgradename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.setUpgradename = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string upgradeDesc = 5;
 * @return {string}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.getUpgradedesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.setUpgradedesc = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 level = 6;
 * @return {number}
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.LegendUpgradeSelected} returns this
 */
proto.rtech.liveapi.LegendUpgradeSelected.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


