// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.LoadoutConfiguration');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.InventoryItem');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.LoadoutConfiguration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rtech.liveapi.LoadoutConfiguration.repeatedFields_, null);
};
goog.inherits(proto.rtech.liveapi.LoadoutConfiguration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.LoadoutConfiguration.displayName = 'proto.rtech.liveapi.LoadoutConfiguration';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rtech.liveapi.LoadoutConfiguration.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.LoadoutConfiguration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.LoadoutConfiguration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.LoadoutConfiguration.toObject = function(includeInstance, msg) {
  var f, obj = {
weaponsList: jspb.Message.toObjectList(msg.getWeaponsList(),
    proto.rtech.liveapi.InventoryItem.toObject, includeInstance),
equipmentList: jspb.Message.toObjectList(msg.getEquipmentList(),
    proto.rtech.liveapi.InventoryItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.LoadoutConfiguration}
 */
proto.rtech.liveapi.LoadoutConfiguration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.LoadoutConfiguration;
  return proto.rtech.liveapi.LoadoutConfiguration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.LoadoutConfiguration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.LoadoutConfiguration}
 */
proto.rtech.liveapi.LoadoutConfiguration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.rtech.liveapi.InventoryItem;
      reader.readMessage(value,proto.rtech.liveapi.InventoryItem.deserializeBinaryFromReader);
      msg.addWeapons(value);
      break;
    case 2:
      var value = new proto.rtech.liveapi.InventoryItem;
      reader.readMessage(value,proto.rtech.liveapi.InventoryItem.deserializeBinaryFromReader);
      msg.addEquipment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.LoadoutConfiguration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.LoadoutConfiguration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.LoadoutConfiguration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWeaponsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.rtech.liveapi.InventoryItem.serializeBinaryToWriter
    );
  }
  f = message.getEquipmentList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.rtech.liveapi.InventoryItem.serializeBinaryToWriter
    );
  }
};


/**
 * repeated InventoryItem weapons = 1;
 * @return {!Array<!proto.rtech.liveapi.InventoryItem>}
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.getWeaponsList = function() {
  return /** @type{!Array<!proto.rtech.liveapi.InventoryItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rtech.liveapi.InventoryItem, 1));
};


/**
 * @param {!Array<!proto.rtech.liveapi.InventoryItem>} value
 * @return {!proto.rtech.liveapi.LoadoutConfiguration} returns this
*/
proto.rtech.liveapi.LoadoutConfiguration.prototype.setWeaponsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.rtech.liveapi.InventoryItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rtech.liveapi.InventoryItem}
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.addWeapons = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.rtech.liveapi.InventoryItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rtech.liveapi.LoadoutConfiguration} returns this
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.clearWeaponsList = function() {
  return this.setWeaponsList([]);
};


/**
 * repeated InventoryItem equipment = 2;
 * @return {!Array<!proto.rtech.liveapi.InventoryItem>}
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.getEquipmentList = function() {
  return /** @type{!Array<!proto.rtech.liveapi.InventoryItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rtech.liveapi.InventoryItem, 2));
};


/**
 * @param {!Array<!proto.rtech.liveapi.InventoryItem>} value
 * @return {!proto.rtech.liveapi.LoadoutConfiguration} returns this
*/
proto.rtech.liveapi.LoadoutConfiguration.prototype.setEquipmentList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.rtech.liveapi.InventoryItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rtech.liveapi.InventoryItem}
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.addEquipment = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.rtech.liveapi.InventoryItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rtech.liveapi.LoadoutConfiguration} returns this
 */
proto.rtech.liveapi.LoadoutConfiguration.prototype.clearEquipmentList = function() {
  return this.setEquipmentList([]);
};


