// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.MatchSetup');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.Datacenter');
goog.require('proto.rtech.liveapi.LoadoutConfiguration');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.MatchSetup = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rtech.liveapi.MatchSetup, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.MatchSetup.displayName = 'proto.rtech.liveapi.MatchSetup';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.MatchSetup.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.MatchSetup.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.MatchSetup} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.MatchSetup.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
category: jspb.Message.getFieldWithDefault(msg, 2, ""),
map: jspb.Message.getFieldWithDefault(msg, 3, ""),
playlistname: jspb.Message.getFieldWithDefault(msg, 4, ""),
playlistdesc: jspb.Message.getFieldWithDefault(msg, 5, ""),
datacenter: (f = msg.getDatacenter()) && proto.rtech.liveapi.Datacenter.toObject(includeInstance, f),
aimassiston: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
anonymousmode: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
serverid: jspb.Message.getFieldWithDefault(msg, 9, ""),
startingloadout: (f = msg.getStartingloadout()) && proto.rtech.liveapi.LoadoutConfiguration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.MatchSetup}
 */
proto.rtech.liveapi.MatchSetup.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.MatchSetup;
  return proto.rtech.liveapi.MatchSetup.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.MatchSetup} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.MatchSetup}
 */
proto.rtech.liveapi.MatchSetup.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMap(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlaylistname(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlaylistdesc(value);
      break;
    case 6:
      var value = new proto.rtech.liveapi.Datacenter;
      reader.readMessage(value,proto.rtech.liveapi.Datacenter.deserializeBinaryFromReader);
      msg.setDatacenter(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAimassiston(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAnonymousmode(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setServerid(value);
      break;
    case 10:
      var value = new proto.rtech.liveapi.LoadoutConfiguration;
      reader.readMessage(value,proto.rtech.liveapi.LoadoutConfiguration.deserializeBinaryFromReader);
      msg.setStartingloadout(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.MatchSetup.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.MatchSetup.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.MatchSetup} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.MatchSetup.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMap();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPlaylistname();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPlaylistdesc();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDatacenter();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.rtech.liveapi.Datacenter.serializeBinaryToWriter
    );
  }
  f = message.getAimassiston();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getAnonymousmode();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getServerid();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getStartingloadout();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.rtech.liveapi.LoadoutConfiguration.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.rtech.liveapi.MatchSetup.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string category = 2;
 * @return {string}
 */
proto.rtech.liveapi.MatchSetup.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string map = 3;
 * @return {string}
 */
proto.rtech.liveapi.MatchSetup.prototype.getMap = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setMap = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string playlistName = 4;
 * @return {string}
 */
proto.rtech.liveapi.MatchSetup.prototype.getPlaylistname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setPlaylistname = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string playlistDesc = 5;
 * @return {string}
 */
proto.rtech.liveapi.MatchSetup.prototype.getPlaylistdesc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setPlaylistdesc = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Datacenter datacenter = 6;
 * @return {?proto.rtech.liveapi.Datacenter}
 */
proto.rtech.liveapi.MatchSetup.prototype.getDatacenter = function() {
  return /** @type{?proto.rtech.liveapi.Datacenter} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Datacenter, 6));
};


/**
 * @param {?proto.rtech.liveapi.Datacenter|undefined} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
*/
proto.rtech.liveapi.MatchSetup.prototype.setDatacenter = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.clearDatacenter = function() {
  return this.setDatacenter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.MatchSetup.prototype.hasDatacenter = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional bool aimAssistOn = 7;
 * @return {boolean}
 */
proto.rtech.liveapi.MatchSetup.prototype.getAimassiston = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setAimassiston = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool anonymousMode = 8;
 * @return {boolean}
 */
proto.rtech.liveapi.MatchSetup.prototype.getAnonymousmode = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setAnonymousmode = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional string serverId = 9;
 * @return {string}
 */
proto.rtech.liveapi.MatchSetup.prototype.getServerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.setServerid = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional LoadoutConfiguration startingLoadout = 10;
 * @return {?proto.rtech.liveapi.LoadoutConfiguration}
 */
proto.rtech.liveapi.MatchSetup.prototype.getStartingloadout = function() {
  return /** @type{?proto.rtech.liveapi.LoadoutConfiguration} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.LoadoutConfiguration, 10));
};


/**
 * @param {?proto.rtech.liveapi.LoadoutConfiguration|undefined} value
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
*/
proto.rtech.liveapi.MatchSetup.prototype.setStartingloadout = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.MatchSetup} returns this
 */
proto.rtech.liveapi.MatchSetup.prototype.clearStartingloadout = function() {
  return this.setStartingloadout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.MatchSetup.prototype.hasStartingloadout = function() {
  return jspb.Message.getField(this, 10) != null;
};


