// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.ObserverSwitched');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.Player');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.ObserverSwitched = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.rtech.liveapi.ObserverSwitched.repeatedFields_, null);
};
goog.inherits(proto.rtech.liveapi.ObserverSwitched, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.ObserverSwitched.displayName = 'proto.rtech.liveapi.ObserverSwitched';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.rtech.liveapi.ObserverSwitched.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.ObserverSwitched.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.ObserverSwitched} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.ObserverSwitched.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
category: jspb.Message.getFieldWithDefault(msg, 2, ""),
observer: (f = msg.getObserver()) && proto.rtech.liveapi.Player.toObject(includeInstance, f),
target: (f = msg.getTarget()) && proto.rtech.liveapi.Player.toObject(includeInstance, f),
targetteamList: jspb.Message.toObjectList(msg.getTargetteamList(),
    proto.rtech.liveapi.Player.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.ObserverSwitched}
 */
proto.rtech.liveapi.ObserverSwitched.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.ObserverSwitched;
  return proto.rtech.liveapi.ObserverSwitched.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.ObserverSwitched} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.ObserverSwitched}
 */
proto.rtech.liveapi.ObserverSwitched.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 3:
      var value = new proto.rtech.liveapi.Player;
      reader.readMessage(value,proto.rtech.liveapi.Player.deserializeBinaryFromReader);
      msg.setObserver(value);
      break;
    case 4:
      var value = new proto.rtech.liveapi.Player;
      reader.readMessage(value,proto.rtech.liveapi.Player.deserializeBinaryFromReader);
      msg.setTarget(value);
      break;
    case 5:
      var value = new proto.rtech.liveapi.Player;
      reader.readMessage(value,proto.rtech.liveapi.Player.deserializeBinaryFromReader);
      msg.addTargetteam(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.ObserverSwitched.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.ObserverSwitched} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.ObserverSwitched.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getObserver();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.rtech.liveapi.Player.serializeBinaryToWriter
    );
  }
  f = message.getTarget();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.rtech.liveapi.Player.serializeBinaryToWriter
    );
  }
  f = message.getTargetteamList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.rtech.liveapi.Player.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
 */
proto.rtech.liveapi.ObserverSwitched.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string category = 2;
 * @return {string}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
 */
proto.rtech.liveapi.ObserverSwitched.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Player observer = 3;
 * @return {?proto.rtech.liveapi.Player}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.getObserver = function() {
  return /** @type{?proto.rtech.liveapi.Player} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Player, 3));
};


/**
 * @param {?proto.rtech.liveapi.Player|undefined} value
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
*/
proto.rtech.liveapi.ObserverSwitched.prototype.setObserver = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
 */
proto.rtech.liveapi.ObserverSwitched.prototype.clearObserver = function() {
  return this.setObserver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.hasObserver = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Player target = 4;
 * @return {?proto.rtech.liveapi.Player}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.getTarget = function() {
  return /** @type{?proto.rtech.liveapi.Player} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Player, 4));
};


/**
 * @param {?proto.rtech.liveapi.Player|undefined} value
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
*/
proto.rtech.liveapi.ObserverSwitched.prototype.setTarget = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
 */
proto.rtech.liveapi.ObserverSwitched.prototype.clearTarget = function() {
  return this.setTarget(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.hasTarget = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated Player targetTeam = 5;
 * @return {!Array<!proto.rtech.liveapi.Player>}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.getTargetteamList = function() {
  return /** @type{!Array<!proto.rtech.liveapi.Player>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.rtech.liveapi.Player, 5));
};


/**
 * @param {!Array<!proto.rtech.liveapi.Player>} value
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
*/
proto.rtech.liveapi.ObserverSwitched.prototype.setTargetteamList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.rtech.liveapi.Player=} opt_value
 * @param {number=} opt_index
 * @return {!proto.rtech.liveapi.Player}
 */
proto.rtech.liveapi.ObserverSwitched.prototype.addTargetteam = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.rtech.liveapi.Player, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.rtech.liveapi.ObserverSwitched} returns this
 */
proto.rtech.liveapi.ObserverSwitched.prototype.clearTargetteamList = function() {
  return this.setTargetteamList([]);
};


