// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.Player');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.Vector3');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.Player = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rtech.liveapi.Player, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.Player.displayName = 'proto.rtech.liveapi.Player';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.Player.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.Player.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.Player} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.Player.toObject = function(includeInstance, msg) {
  var f, obj = {
name: jspb.Message.getFieldWithDefault(msg, 1, ""),
teamid: jspb.Message.getFieldWithDefault(msg, 2, 0),
pos: (f = msg.getPos()) && proto.rtech.liveapi.Vector3.toObject(includeInstance, f),
angles: (f = msg.getAngles()) && proto.rtech.liveapi.Vector3.toObject(includeInstance, f),
currenthealth: jspb.Message.getFieldWithDefault(msg, 5, 0),
maxhealth: jspb.Message.getFieldWithDefault(msg, 6, 0),
shieldhealth: jspb.Message.getFieldWithDefault(msg, 7, 0),
shieldmaxhealth: jspb.Message.getFieldWithDefault(msg, 8, 0),
nucleushash: jspb.Message.getFieldWithDefault(msg, 9, ""),
hardwarename: jspb.Message.getFieldWithDefault(msg, 10, ""),
teamname: jspb.Message.getFieldWithDefault(msg, 11, ""),
squadindex: jspb.Message.getFieldWithDefault(msg, 12, 0),
character: jspb.Message.getFieldWithDefault(msg, 13, ""),
skin: jspb.Message.getFieldWithDefault(msg, 14, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.Player}
 */
proto.rtech.liveapi.Player.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.Player;
  return proto.rtech.liveapi.Player.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.Player} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.Player}
 */
proto.rtech.liveapi.Player.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTeamid(value);
      break;
    case 3:
      var value = new proto.rtech.liveapi.Vector3;
      reader.readMessage(value,proto.rtech.liveapi.Vector3.deserializeBinaryFromReader);
      msg.setPos(value);
      break;
    case 4:
      var value = new proto.rtech.liveapi.Vector3;
      reader.readMessage(value,proto.rtech.liveapi.Vector3.deserializeBinaryFromReader);
      msg.setAngles(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCurrenthealth(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxhealth(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setShieldhealth(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setShieldmaxhealth(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setNucleushash(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setHardwarename(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeamname(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSquadindex(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCharacter(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkin(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.Player.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.Player.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.Player} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.Player.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTeamid();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getPos();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.rtech.liveapi.Vector3.serializeBinaryToWriter
    );
  }
  f = message.getAngles();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.rtech.liveapi.Vector3.serializeBinaryToWriter
    );
  }
  f = message.getCurrenthealth();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getMaxhealth();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getShieldhealth();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getShieldmaxhealth();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getNucleushash();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getHardwarename();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getTeamname();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getSquadindex();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getCharacter();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getSkin();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.rtech.liveapi.Player.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional uint32 teamId = 2;
 * @return {number}
 */
proto.rtech.liveapi.Player.prototype.getTeamid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setTeamid = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional Vector3 pos = 3;
 * @return {?proto.rtech.liveapi.Vector3}
 */
proto.rtech.liveapi.Player.prototype.getPos = function() {
  return /** @type{?proto.rtech.liveapi.Vector3} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Vector3, 3));
};


/**
 * @param {?proto.rtech.liveapi.Vector3|undefined} value
 * @return {!proto.rtech.liveapi.Player} returns this
*/
proto.rtech.liveapi.Player.prototype.setPos = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.clearPos = function() {
  return this.setPos(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.Player.prototype.hasPos = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Vector3 angles = 4;
 * @return {?proto.rtech.liveapi.Vector3}
 */
proto.rtech.liveapi.Player.prototype.getAngles = function() {
  return /** @type{?proto.rtech.liveapi.Vector3} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Vector3, 4));
};


/**
 * @param {?proto.rtech.liveapi.Vector3|undefined} value
 * @return {!proto.rtech.liveapi.Player} returns this
*/
proto.rtech.liveapi.Player.prototype.setAngles = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.clearAngles = function() {
  return this.setAngles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.Player.prototype.hasAngles = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional uint32 currentHealth = 5;
 * @return {number}
 */
proto.rtech.liveapi.Player.prototype.getCurrenthealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setCurrenthealth = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 maxHealth = 6;
 * @return {number}
 */
proto.rtech.liveapi.Player.prototype.getMaxhealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setMaxhealth = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 shieldHealth = 7;
 * @return {number}
 */
proto.rtech.liveapi.Player.prototype.getShieldhealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setShieldhealth = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 shieldMaxHealth = 8;
 * @return {number}
 */
proto.rtech.liveapi.Player.prototype.getShieldmaxhealth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setShieldmaxhealth = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string nucleusHash = 9;
 * @return {string}
 */
proto.rtech.liveapi.Player.prototype.getNucleushash = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setNucleushash = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string hardwareName = 10;
 * @return {string}
 */
proto.rtech.liveapi.Player.prototype.getHardwarename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setHardwarename = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string teamName = 11;
 * @return {string}
 */
proto.rtech.liveapi.Player.prototype.getTeamname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setTeamname = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional uint32 squadIndex = 12;
 * @return {number}
 */
proto.rtech.liveapi.Player.prototype.getSquadindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setSquadindex = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional string character = 13;
 * @return {string}
 */
proto.rtech.liveapi.Player.prototype.getCharacter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setCharacter = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string skin = 14;
 * @return {string}
 */
proto.rtech.liveapi.Player.prototype.getSkin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.Player} returns this
 */
proto.rtech.liveapi.Player.prototype.setSkin = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


