// source: events.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.rtech.liveapi.RingFinishedClosing');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.rtech.liveapi.Vector3');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.rtech.liveapi.RingFinishedClosing = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.rtech.liveapi.RingFinishedClosing, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.rtech.liveapi.RingFinishedClosing.displayName = 'proto.rtech.liveapi.RingFinishedClosing';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.toObject = function(opt_includeInstance) {
  return proto.rtech.liveapi.RingFinishedClosing.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.rtech.liveapi.RingFinishedClosing} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.RingFinishedClosing.toObject = function(includeInstance, msg) {
  var f, obj = {
timestamp: jspb.Message.getFieldWithDefault(msg, 1, 0),
category: jspb.Message.getFieldWithDefault(msg, 2, ""),
stage: jspb.Message.getFieldWithDefault(msg, 3, 0),
center: (f = msg.getCenter()) && proto.rtech.liveapi.Vector3.toObject(includeInstance, f),
currentradius: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
shrinkduration: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.rtech.liveapi.RingFinishedClosing}
 */
proto.rtech.liveapi.RingFinishedClosing.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.rtech.liveapi.RingFinishedClosing;
  return proto.rtech.liveapi.RingFinishedClosing.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.rtech.liveapi.RingFinishedClosing} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.rtech.liveapi.RingFinishedClosing}
 */
proto.rtech.liveapi.RingFinishedClosing.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStage(value);
      break;
    case 4:
      var value = new proto.rtech.liveapi.Vector3;
      reader.readMessage(value,proto.rtech.liveapi.Vector3.deserializeBinaryFromReader);
      msg.setCenter(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCurrentradius(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setShrinkduration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.rtech.liveapi.RingFinishedClosing.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.rtech.liveapi.RingFinishedClosing} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.rtech.liveapi.RingFinishedClosing.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStage();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getCenter();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.rtech.liveapi.Vector3.serializeBinaryToWriter
    );
  }
  f = message.getCurrentradius();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getShrinkduration();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
};


/**
 * optional uint64 timestamp = 1;
 * @return {number}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.setTimestamp = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string category = 2;
 * @return {string}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 stage = 3;
 * @return {number}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.getStage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.setStage = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional Vector3 center = 4;
 * @return {?proto.rtech.liveapi.Vector3}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.getCenter = function() {
  return /** @type{?proto.rtech.liveapi.Vector3} */ (
    jspb.Message.getWrapperField(this, proto.rtech.liveapi.Vector3, 4));
};


/**
 * @param {?proto.rtech.liveapi.Vector3|undefined} value
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
*/
proto.rtech.liveapi.RingFinishedClosing.prototype.setCenter = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.clearCenter = function() {
  return this.setCenter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.hasCenter = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional float currentRadius = 5;
 * @return {number}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.getCurrentradius = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.setCurrentradius = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float shrinkDuration = 7;
 * @return {number}
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.getShrinkduration = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.rtech.liveapi.RingFinishedClosing} returns this
 */
proto.rtech.liveapi.RingFinishedClosing.prototype.setShrinkduration = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


