const {
    Init, Vector3, Player, CustomMatch_LobbyPlayer, Datacenter, Version, InventoryItem, LoadoutConfiguration,
    CustomMatch_LobbyPlayers, RequestStatus, Response, MatchSetup, GameStateChanged, CharacterSelected, MatchStateEnd, RingStartClosing,
    RingFinishedClosing, PlayerConnected, PlayerDisconnected, PlayerStatChanged, PlayerUpgradeTierChanged, PlayerDamaged,
    PlayerKilled, PlayerDowned, PlayerAssist, SquadEliminated, GibraltarShieldAbsorbed, RevenantForgedShadowDamaged,
    PlayerRespawnTeam, PlayerRevive, ArenasItemSelected, ArenasItemDeselected, InventoryPickUp, InventoryDrop, InventoryUse,
    BannerCollected, PlayerAbilityUsed, LegendUpgradeSelected, ZiplineUsed, GrenadeThrown, BlackMarketAction, WraithPortal,
    WarpGateUsed, AmmoUsed, WeaponSwitched, ObserverSwitched, ObserverAnnotation
  } = require('../bin/events_pb');
  
  const messageTypes = {
    'type.googleapis.com/rtech.liveapi.Init': Init,
    'type.googleapis.com/rtech.liveapi.Vector3': Vector3,
    'type.googleapis.com/rtech.liveapi.Player': Player,
    'type.googleapis.com/rtech.liveapi.CustomMatch_LobbyPlayer': CustomMatch_LobbyPlayer,
    'type.googleapis.com/rtech.liveapi.Datacenter': Datacenter,
    'type.googleapis.com/rtech.liveapi.Version': Version,
    'type.googleapis.com/rtech.liveapi.InventoryItem': InventoryItem,
    'type.googleapis.com/rtech.liveapi.LoadoutConfiguration': LoadoutConfiguration,
    'type.googleapis.com/rtech.liveapi.CustomMatch_LobbyPlayers': CustomMatch_LobbyPlayers,
    'type.googleapis.com/rtech.liveapi.RequestStatus': RequestStatus,
    'type.googleapis.com/rtech.liveapi.Response': Response,
    'type.googleapis.com/rtech.liveapi.MatchSetup': MatchSetup,
    'type.googleapis.com/rtech.liveapi.GameStateChanged': GameStateChanged,
    'type.googleapis.com/rtech.liveapi.CharacterSelected': CharacterSelected,
    'type.googleapis.com/rtech.liveapi.MatchStateEnd': MatchStateEnd,
    'type.googleapis.com/rtech.liveapi.RingStartClosing': RingStartClosing,
    'type.googleapis.com/rtech.liveapi.RingFinishedClosing': RingFinishedClosing,
    'type.googleapis.com/rtech.liveapi.PlayerConnected': PlayerConnected,
    'type.googleapis.com/rtech.liveapi.PlayerDisconnected': PlayerDisconnected,
    'type.googleapis.com/rtech.liveapi.PlayerStatChanged': PlayerStatChanged,
    'type.googleapis.com/rtech.liveapi.PlayerUpgradeTierChanged': PlayerUpgradeTierChanged,
    'type.googleapis.com/rtech.liveapi.PlayerDamaged': PlayerDamaged,
    'type.googleapis.com/rtech.liveapi.PlayerKilled': PlayerKilled,
    'type.googleapis.com/rtech.liveapi.PlayerDowned': PlayerDowned,
    'type.googleapis.com/rtech.liveapi.PlayerAssist': PlayerAssist,
    'type.googleapis.com/rtech.liveapi.SquadEliminated': SquadEliminated,
    'type.googleapis.com/rtech.liveapi.GibraltarShieldAbsorbed': GibraltarShieldAbsorbed,
    'type.googleapis.com/rtech.liveapi.RevenantForgedShadowDamaged': RevenantForgedShadowDamaged,
    'type.googleapis.com/rtech.liveapi.PlayerRespawnTeam': PlayerRespawnTeam,
    'type.googleapis.com/rtech.liveapi.PlayerRevive': PlayerRevive,
    'type.googleapis.com/rtech.liveapi.ArenasItemSelected': ArenasItemSelected,
    'type.googleapis.com/rtech.liveapi.ArenasItemDeselected': ArenasItemDeselected,
    'type.googleapis.com/rtech.liveapi.InventoryPickUp': InventoryPickUp,
    'type.googleapis.com/rtech.liveapi.InventoryDrop': InventoryDrop,
    'type.googleapis.com/rtech.liveapi.InventoryUse': InventoryUse,
    'type.googleapis.com/rtech.liveapi.BannerCollected': BannerCollected,
    'type.googleapis.com/rtech.liveapi.PlayerAbilityUsed': PlayerAbilityUsed,
    'type.googleapis.com/rtech.liveapi.LegendUpgradeSelected': LegendUpgradeSelected,
    'type.googleapis.com/rtech.liveapi.ZiplineUsed': ZiplineUsed,
    'type.googleapis.com/rtech.liveapi.GrenadeThrown': GrenadeThrown,
    'type.googleapis.com/rtech.liveapi.BlackMarketAction': BlackMarketAction,
    'type.googleapis.com/rtech.liveapi.WraithPortal': WraithPortal,
    'type.googleapis.com/rtech.liveapi.WarpGateUsed': WarpGateUsed,
    'type.googleapis.com/rtech.liveapi.AmmoUsed': AmmoUsed,
    'type.googleapis.com/rtech.liveapi.WeaponSwitched': WeaponSwitched,
    'type.googleapis.com/rtech.liveapi.ObserverSwitched': ObserverSwitched,
    'type.googleapis.com/rtech.liveapi.ObserverAnnotation': ObserverAnnotation
  };
  
  module.exports = messageTypes;
  